import ProjectDescription

let workspace = Workspace(
    name: "ExampleCode",
    projects: [""],
    generationOptions: .options(enableAutomaticXcodeSchemes: false, autogeneratedWorkspaceSchemes: .disabled)
)
